# Schema file for class "Def"

prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix amora:<http://amora.center/kb/amora/Schema/0.1/>
prefix decl:<http://amora.center/kb/amora/Schema/0.1/Decl/0.1/>
prefix schema:<http://amora.center/kb/amora/Schema/0.1/Def/0.1/>

insert data {
  # schema data
  schema: amora:schemaName "Def" .
  schema: amora:schemaVersion "0.1" .
  schema: amora:schemaAuthor "amora" .
  schema: amora:schemaId schema:name .
  schema: amora:schemaId schema:owner .
  schema: amora:schemaId schema:flag .
  schema: amora:schemaId schema:posStart .
  schema: amora:schemaId schema:posEnd .
  schema: amora:schemaId schema:jvmSignature .
  schema: amora:format <http://amora.center/kb/amora/Format/0.1/amora/Def/0.1/schema.jsonld> .

  # inference rules
  schema:name rdfs:subPropertyOf decl:name .
  schema:owner rdfs:subPropertyOf decl:owner .
  schema:flag rdfs:subPropertyOf decl:flag .
  schema:posStart rdfs:subPropertyOf decl:posStart .
  schema:posEnd rdfs:subPropertyOf decl:posEnd .
  schema: rdfs:subClassOf decl: .
}
